---
- hosts: localhost
  vars_files:
    - request-roks-vars.yml
  collections:
    - ibm.cloudcollection

  tasks:
    - name: create roks vpc cluster
      import_role: 
        name: request_ocp_roks_vpc
